name: Print some text every 3rd minute
on:
  schedule:
    - cron: '* * * * *'

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      -name: Print some text
       run: echo "Periodically printing passages"
