name: Generate Report

on:
  schedule:
    - cron: "* * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    # Reduced the code for brevity
    - name: Generate report and Send email
      run: |
        generate-report.sh 
        send-email.sh
